# Generated by Django 4.1.4 on 2022-12-29 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnamneseGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixaPrincipal', models.CharField(max_length=1024, verbose_name='Queixa Principal')),
                ('historicoDoencaAtual', models.CharField(max_length=1024, verbose_name='Histórico de Doença Atual')),
                ('antecedentesMorbidos', models.CharField(max_length=1024, verbose_name='Antecedentes Mórbidos')),
                ('CondicaoDeVida', models.CharField(max_length=1024, verbose_name='Condição de Vida')),
            ],
        ),
        migrations.CreateModel(
            name='Medicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeRemedio', models.CharField(max_length=256, verbose_name='Nome do medicamento')),
                ('dose', models.CharField(max_length=4, verbose_name='Dose(Mg/Kg)')),
                ('frequencia', models.CharField(max_length=64, verbose_name='Frequencia')),
                ('duracao', models.CharField(max_length=10, verbose_name='Duração')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome do Proprietario')),
                ('rg', models.CharField(max_length=256, verbose_name='RG do Proprietario')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF fo Proprietario')),
                ('celularTelefone', models.CharField(max_length=15, verbose_name='Telefone para Contato')),
                ('endereco', models.CharField(max_length=512, verbose_name='Local de Residencia do Proprietario')),
                ('email', models.CharField(max_length=128, verbose_name='Email para Contato')),
            ],
            options={
                'db_table': 'proprietario',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome do Paciente')),
                ('especie', models.CharField(choices=[('CANINO', 'CANINO'), ('FELINO', 'FELINO'), ('OUTROS', 'OUTROS')], max_length=16, verbose_name='Espécie do Paciente')),
                ('raca', models.CharField(choices=[('RAÇAS CANINAS', (('Akita', 'Akita'), ('Basset hound', 'Basset hound'), ('Beagle', 'Beagle'), ('Bichon frisé', 'Bichon frisé'), ('Boiadeiro australiano', 'Boiadeiro australiano'), ('Border collie', 'Border collie'), ('Boston terrier', 'Boston terrier'), ('Boxer', 'Boxer'), ('Buldogue francês', 'Buldogue francês'), ('Buldogue inglês', 'Buldogue inglês'), ('Bull terrier', 'Bull terrier'), ('Cane corso', 'Cane corso'), ('Cavalier king charles spaniel', 'Cavalier king charles spaniel'), ('Chihuahua', 'Chihuahua'), ('Chow chow', 'Chow chow'), ('Cocker spaniel inglês', 'Cocker spaniel inglês'), ('Dachshund', 'Dachshund'), ('Dálmata', 'Dálmata'), ('Doberman', 'Doberman'), ('Dogo argentino', 'Dogo argentino'), ('Dogue alemão', 'Dogue alemão'), ('Fila brasileiro', 'Fila brasileiro'), ('Golden retriever', 'Golden retriever'), ('Husky siberiano', 'Husky siberiano'), ('Jack russell terrier', 'Jack russell terrier'), ('Labrador retriever', 'Labrador retriever'), ('Lhasa apso', 'Lhasa apso'), ('Lulu da pomerânia', 'Lulu da pomerânia'), ('Maltês', 'Maltês'), ('Mastiff inglês', 'Mastiff inglês'), ('Mastim tibetano', 'Mastim tibetano'), ('Pastor alemão', 'Pastor alemão'), ('Pastor australiano', 'Pastor australiano'), ('Pastor de Shetland', 'Pastor de Shetland'), ('Pequinês', 'Pequinês'), ('Pinscher', 'Pinscher'), ('Pit bull', 'Pit bull'), ('Poodle', 'Poodle'), ('Pug', 'Pug'), ('Rottweiler', 'Rottweiler'), ('Schnauzer', 'Schnauzer'), ('Shar-pei', 'Shar-pei'), ('Shiba', 'Shiba'), ('Shih tzu', 'Shih tzu'), ('Staffordshire bull terrier', 'Staffordshire bull terrier'), ('Weimaraner', 'Weimaraner'), ('Yorkshire', 'Yorkshire'), ('--------', '--------'))), ('RAÇAS FELINAS', (('Abissínio', 'Abissínio'), ('Angorá', 'Angorá'), ('Ashera', 'Ashera'), ('Balinês', 'Balinês'), ('Bengal', 'Bengal'), ('Bobtail americano', 'Bobtail americano'), ('Bobtail japonês', 'Bobtail japonês'), ('Bombay', 'Bombay'), ('Burmês', 'Burmês'), ('Chartreux', 'Chartreux'), ('Colorpoint de Pêlo Curto', 'Colorpoint de Pêlo Curto'), ('Cornish Rex', 'Cornish Rex'), ('Curl Americano', 'Curl Americano'), ('Devon Rex', 'Devon Rex'), ('Himalaio', 'Himalaio'), ('Jaguatirica', 'Jaguatirica'), ('Javanês', 'Javanês'), ('Korat', 'Korat'), ('LaPerm', 'LaPerm'), ('Maine Coon', 'Maine Coon'), ('Manx', 'Manx'), ('Cymric', 'Cymric'), ('Mau Egípcio', 'Mau Egípcio'), ('Mist Australiano', 'Mist Australiano'), ('Munchkin', 'Munchkin'), ('Norueguês da Floresta', 'Norueguês da Floresta'), ('Pelo curto americano', 'Pelo curto americano'), ('Pelo curto brasileiro', 'Pelo curto brasileiro'), ('Pelo curto europeu', 'Pelo curto europeu'), ('Pelo curto inglês', 'Pelo curto inglês'), ('Pelo curto Oriental', 'Pelo curto Oriental'), ('Persa', 'Persa'), ('Pixie-bob', 'Pixie-bob'), ('Ragdoll', 'Ragdoll'), ('Ocicat', 'Ocicat'), ('Russo Azul', 'Russo Azul'), ('Sagrado da Birmânia', 'Sagrado da Birmânia'), ('Savannah', 'Savannah'), ('Scottish Fold', 'Scottish Fold'), ('Selkirk Rex', 'Selkirk Rex'), ('Siamês', 'Siamês'), ('Siberiano', 'Siberiano'), ('Singapura', 'Singapura'), ('Somali', 'Somali'), ('Sphynx', 'Sphynx'), ('Thai', 'Thai'), ('Tonquinês', 'Tonquinês'), ('Toyger', 'Toyger'), ('Usuri', 'Usuri'), ('Sem raça definida (SRD)', 'Sem raça definida (SRD)')))], max_length=32, verbose_name='Raça do Paciente')),
                ('idade', models.CharField(max_length=3, verbose_name='Idade do Paciente')),
                ('sexo', models.CharField(choices=[('MACHO', 'MACHO'), ('FÊMEA', 'FÊMEA')], max_length=64, null=True, verbose_name='Sexo do Paciente')),
                ('corPelagem', models.CharField(choices=[('CORES CANINAS', (('Marrom', 'Marrom'), ('Caramelo', 'Caramelo'), ('Preto', 'Preto'), ('Cinza', 'Cinza'), ('Bicolor', 'Bicolor'), ('Tricolor', 'Tricolor'))), ('CORES FELINAS', (('Azul', 'Azul'), ('Bege', 'Bege'), ('Branco', 'Branco'), ('Canela e Chocolate', 'Canela e Chocolate'), ('Chocolate', 'Chocolate'), ('Cinza', 'Cinza'), ('Creme', 'Creme'), ('Lilás', 'Lilás'), ('Marrom-escuro', 'Marrom-escuro'), ('Negro', 'Negro'), ('Vermelho', 'Vermelho')))], max_length=64, verbose_name='Cor do pelo do Paciente')),
                ('dataEntrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada do Paciente')),
                ('proprietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.proprietario')),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoesAdd', models.CharField(max_length=2048, verbose_name='Observações Adicionais')),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.anamnesegeral')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ExameObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperaturaRetal', models.CharField(max_length=1024, verbose_name='Temperatúra Retal Cº')),
                ('ectoscopia', models.CharField(max_length=1024, verbose_name='Ectoscopia')),
                ('srNariz', models.CharField(max_length=1024, verbose_name='S.R. Nariz')),
                ('srTorazInspecaoFr', models.CharField(max_length=1024, verbose_name='S.R. Tórax (Inspeção F.R)')),
                ('tipoMovimento', models.CharField(max_length=1024, verbose_name='Tipo de movimento')),
                ('polpacao', models.CharField(max_length=1024, verbose_name='Polpação')),
                ('percussao', models.CharField(max_length=1024, verbose_name='Percussão')),
                ('aucusticaPulmonar', models.CharField(max_length=1024, verbose_name='Aucústica Pulmonar')),
                ('scCoracaoFc', models.CharField(max_length=1024, verbose_name='S.C. Coração F.C.')),
                ('ritmo', models.CharField(max_length=1024, verbose_name='Ritmo')),
                ('aucusticaPalpacao', models.CharField(max_length=1024, verbose_name='Aucústica Palpação')),
                ('pulsoArterial', models.CharField(max_length=1024, verbose_name='Pulso Arterial')),
                ('alteracoesVasculares', models.CharField(max_length=1024, verbose_name='Alterações Vasculares')),
                ('shlLifonodos', models.CharField(max_length=1024, verbose_name='S.H.L Linfonodos')),
                ('baco', models.CharField(max_length=1024, verbose_name='Baço')),
                ('sdViasDigestoriasAnteriores', models.CharField(max_length=1024, verbose_name='S.D. Vias Digestórias Anteriores')),
                ('abdomen', models.CharField(max_length=1024, verbose_name='Abdomen')),
                ('estomago', models.CharField(max_length=1024, verbose_name='Estomago')),
                ('intestinos', models.CharField(max_length=1024, verbose_name='Intestinos')),
                ('figado', models.CharField(max_length=1024, verbose_name='Figado')),
                ('sgu', models.CharField(max_length=1024, verbose_name='S.G.U')),
                ('sn', models.CharField(max_length=1024, verbose_name='S.N.')),
                ('orgaosSentidosOlhosOuvidos', models.CharField(max_length=1024, verbose_name='Orgão dos Sentidos, Olhos e Ouvidos')),
                ('aparelhoLocomotor', models.CharField(max_length=1024, verbose_name='Aparelho Locomotor')),
                ('apreciacaoAchados', models.CharField(max_length=1024, verbose_name='Apreciação dos Achados')),
                ('diagProvisorio', models.CharField(max_length=1024, verbose_name='Diagnóstico Provisório')),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.anamnesegeral')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ExameComplementar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examesComplementares', models.CharField(max_length=1024, verbose_name='Exames Complementares')),
                ('anexo', models.FileField(upload_to='base')),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.anamnesegeral')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Conclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagPrincipal', models.CharField(max_length=1024, verbose_name='Diagnóstico Principal')),
                ('outrosDiags', models.CharField(max_length=1024, verbose_name='Outros Diagnósticos')),
                ('prognostico', models.CharField(max_length=1024, verbose_name='Prognóstico')),
                ('tratamentoPrescrito', models.CharField(max_length=1024, verbose_name='Tratamento Prescrito')),
                ('obs', models.CharField(max_length=1024, verbose_name='OBS')),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.anamnesegeral')),
                ('medicacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.medicacao')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='anamnesegeral',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente'),
        ),
        migrations.CreateModel(
            name='AnamneseEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olhos', models.CharField(max_length=1024, verbose_name='Olhos')),
                ('ouvidos', models.CharField(max_length=1024, verbose_name='Ouvidos')),
                ('sr', models.CharField(max_length=1024, verbose_name='S.R.')),
                ('sc', models.CharField(max_length=1024, verbose_name='S.C.')),
                ('sd', models.CharField(max_length=1024, verbose_name='S.D.')),
                ('sgu', models.CharField(max_length=1024, verbose_name='S.G.U.')),
                ('sn', models.CharField(max_length=1024, verbose_name='S.N.')),
                ('historicoImunizacao', models.CharField(max_length=1024, verbose_name='Histórico de imunização')),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.anamnesegeral')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
    ]
