# Generated by Django 4.1.4 on 2022-12-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome do Proprietario')),
                ('rg', models.CharField(max_length=256, verbose_name='RG do Proprietario')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF fo Proprietario')),
                ('celularTelefone', models.CharField(max_length=15, verbose_name='Telefone para Contato')),
                ('endereco', models.CharField(max_length=512, verbose_name='Local de Residencia do Proprietario')),
                ('email', models.CharField(max_length=128, verbose_name='Email para Contato')),
            ],
            options={
                'db_table': 'proprietario',
            },
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='paciente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paciente.proprietario'),
        ),
    ]
