# Generated by Django 4.1.4 on 2022-12-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_proprietario_alter_paciente_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='corPelagem',
            field=models.CharField(choices=[('CORES CANINAS', (('Marrom', 'Marrom'), ('Caramelo', 'Caramelo'), ('Preto', 'Preto'), ('Cinza', 'Cinza'), ('Bicolor', 'Bicolor'), ('Tricolor', 'Tricolor'))), ('CORES FELINAS', (('Azul', 'Azul'), ('Bege', 'Bege'), ('Branco', 'Branco'), ('Canela e Chocolate', 'Canela e Chocolate'), ('Chocolate', 'Chocolate'), ('Cinza', 'Cinza'), ('Creme', 'Creme'), ('Lilás', 'Lilás'), ('Marrom-escuro', 'Marrom-escuro'), ('Negro', 'Negro'), ('Vermelho', 'Vermelho')))], max_length=64, verbose_name='Cor do pelo do Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='raca',
            field=models.CharField(choices=[('RAÇAS CANINAS', (('Akita', 'Akita'), ('Basset hound', 'Basset hound'), ('Beagle', 'Beagle'), ('Bichon frisé', 'Bichon frisé'), ('Boiadeiro australiano', 'Boiadeiro australiano'), ('Border collie', 'Border collie'), ('Boston terrier', 'Boston terrier'), ('Boxer', 'Boxer'), ('Buldogue francês', 'Buldogue francês'), ('Buldogue inglês', 'Buldogue inglês'), ('Bull terrier', 'Bull terrier'), ('Cane corso', 'Cane corso'), ('Cavalier king charles spaniel', 'Cavalier king charles spaniel'), ('Chihuahua', 'Chihuahua'), ('Chow chow', 'Chow chow'), ('Cocker spaniel inglês', 'Cocker spaniel inglês'), ('Dachshund', 'Dachshund'), ('Dálmata', 'Dálmata'), ('Doberman', 'Doberman'), ('Dogo argentino', 'Dogo argentino'), ('Dogue alemão', 'Dogue alemão'), ('Fila brasileiro', 'Fila brasileiro'), ('Golden retriever', 'Golden retriever'), ('Husky siberiano', 'Husky siberiano'), ('Jack russell terrier', 'Jack russell terrier'), ('Labrador retriever', 'Labrador retriever'), ('Lhasa apso', 'Lhasa apso'), ('Lulu da pomerânia', 'Lulu da pomerânia'), ('Maltês', 'Maltês'), ('Mastiff inglês', 'Mastiff inglês'), ('Mastim tibetano', 'Mastim tibetano'), ('Pastor alemão', 'Pastor alemão'), ('Pastor australiano', 'Pastor australiano'), ('Pastor de Shetland', 'Pastor de Shetland'), ('Pequinês', 'Pequinês'), ('Pinscher', 'Pinscher'), ('Pit bull', 'Pit bull'), ('Poodle', 'Poodle'), ('Pug', 'Pug'), ('Rottweiler', 'Rottweiler'), ('Schnauzer', 'Schnauzer'), ('Shar-pei', 'Shar-pei'), ('Shiba', 'Shiba'), ('Shih tzu', 'Shih tzu'), ('Staffordshire bull terrier', 'Staffordshire bull terrier'), ('Weimaraner', 'Weimaraner'), ('Yorkshire', 'Yorkshire'), ('--------', '--------'))), ('RAÇAS FELINAS', (('Abissínio', 'Abissínio'), ('Angorá', 'Angorá'), ('Ashera', 'Ashera'), ('Balinês', 'Balinês'), ('Bengal', 'Bengal'), ('Bobtail americano', 'Bobtail americano'), ('Bobtail japonês', 'Bobtail japonês'), ('Bombay', 'Bombay'), ('Burmês', 'Burmês'), ('Chartreux', 'Chartreux'), ('Colorpoint de Pêlo Curto', 'Colorpoint de Pêlo Curto'), ('Cornish Rex', 'Cornish Rex'), ('Curl Americano', 'Curl Americano'), ('Devon Rex', 'Devon Rex'), ('Himalaio', 'Himalaio'), ('Jaguatirica', 'Jaguatirica'), ('Javanês', 'Javanês'), ('Korat', 'Korat'), ('LaPerm', 'LaPerm'), ('Maine Coon', 'Maine Coon'), ('Manx', 'Manx'), ('Cymric', 'Cymric'), ('Mau Egípcio', 'Mau Egípcio'), ('Mist Australiano', 'Mist Australiano'), ('Munchkin', 'Munchkin'), ('Norueguês da Floresta', 'Norueguês da Floresta'), ('Pelo curto americano', 'Pelo curto americano'), ('Pelo curto brasileiro', 'Pelo curto brasileiro'), ('Pelo curto europeu', 'Pelo curto europeu'), ('Pelo curto inglês', 'Pelo curto inglês'), ('Pelo curto Oriental', 'Pelo curto Oriental'), ('Persa', 'Persa'), ('Pixie-bob', 'Pixie-bob'), ('Ragdoll', 'Ragdoll'), ('Ocicat', 'Ocicat'), ('Russo Azul', 'Russo Azul'), ('Sagrado da Birmânia', 'Sagrado da Birmânia'), ('Savannah', 'Savannah'), ('Scottish Fold', 'Scottish Fold'), ('Selkirk Rex', 'Selkirk Rex'), ('Siamês', 'Siamês'), ('Siberiano', 'Siberiano'), ('Singapura', 'Singapura'), ('Somali', 'Somali'), ('Sphynx', 'Sphynx'), ('Thai', 'Thai'), ('Tonquinês', 'Tonquinês'), ('Toyger', 'Toyger'), ('Usuri', 'Usuri'), ('Sem raça definida (SRD)', 'Sem raça definida (SRD)')))], max_length=32, verbose_name='Raça do Paciente'),
        ),
    ]
