# Generated by Django 4.1.4 on 2022-12-15 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_paciente_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='observacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoesAdd', models.CharField(max_length=2048, verbose_name='Observações Adicionais')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Medicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeRemedio', models.CharField(max_length=256, verbose_name='Nome do medicamento')),
                ('dose', models.CharField(max_length=4, verbose_name='Dose(Mg/Kg)')),
                ('frequencia', models.CharField(max_length=64, verbose_name='Frequencia')),
                ('duracao', models.CharField(max_length=10, verbose_name='Duração')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ExamesComplementares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examesComplementares', models.CharField(max_length=1024, verbose_name='Exames Complementares')),
                ('anexo', models.FileField(upload_to='base')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='exameObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperaturaRetal', models.CharField(max_length=1024, verbose_name='Temperatúra Retal Cº')),
                ('ectoscopia', models.CharField(max_length=1024, verbose_name='Ectoscopia')),
                ('srNariz', models.CharField(max_length=1024, verbose_name='S.R. Nariz')),
                ('srTorazInspecaoFr', models.CharField(max_length=1024, verbose_name='S.R. Tórax (Inspeção F.R)')),
                ('tipoMovimento', models.CharField(max_length=1024, verbose_name='Tipo de movimento')),
                ('polpacao', models.CharField(max_length=1024, verbose_name='Polpação')),
                ('percussao', models.CharField(max_length=1024, verbose_name='Percussão')),
                ('aucusticaPulmonar', models.CharField(max_length=1024, verbose_name='Aucústica Pulmonar')),
                ('scCoracaoFc', models.CharField(max_length=1024, verbose_name='S.C. Coração F.C.')),
                ('ritmo', models.CharField(max_length=1024, verbose_name='Ritmo')),
                ('aucusticaPalpacao', models.CharField(max_length=1024, verbose_name='Aucústica Palpação')),
                ('pulsoArterial', models.CharField(max_length=1024, verbose_name='Pulso Arterial')),
                ('alteracoesVasculares', models.CharField(max_length=1024, verbose_name='Alterações Vasculares')),
                ('shlLifonodos', models.CharField(max_length=1024, verbose_name='S.H.L Linfonodos')),
                ('baco', models.CharField(max_length=1024, verbose_name='Baço')),
                ('sdViasDigestoriasAnteriores', models.CharField(max_length=1024, verbose_name='S.D. Vias Digestórias Anteriores')),
                ('abdomen', models.CharField(max_length=1024, verbose_name='Abdomen')),
                ('estomago', models.CharField(max_length=1024, verbose_name='Estomago')),
                ('intestinos', models.CharField(max_length=1024, verbose_name='Intestinos')),
                ('figado', models.CharField(max_length=1024, verbose_name='Figado')),
                ('sgu', models.CharField(max_length=1024, verbose_name='S.G.U')),
                ('sn', models.CharField(max_length=1024, verbose_name='S.N.')),
                ('orgaosSentidosOlhosOuvidos', models.CharField(max_length=1024, verbose_name='Orgão dos Sentidos, Olhos e Ouvidos')),
                ('aparelhoLocomotor', models.CharField(max_length=1024, verbose_name='Aparelho Locomotor')),
                ('apreciacaoAchados', models.CharField(max_length=1024, verbose_name='Apreciação dos Achados')),
                ('diagProvisorio', models.CharField(max_length=1024, verbose_name='Diagnóstico Provisório')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='conclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagPrincipal', models.CharField(max_length=1024, verbose_name='Diagnóstico Principal')),
                ('outrosDiags', models.CharField(max_length=1024, verbose_name='Outros Diagnósticos')),
                ('prognostico', models.CharField(max_length=1024, verbose_name='Prognóstico')),
                ('tratamentoPrescrito', models.CharField(max_length=1024, verbose_name='Tratamento Prescrito')),
                ('obs', models.CharField(max_length=1024, verbose_name='OBS')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AnamneseGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixaPrincipal', models.CharField(max_length=1024, verbose_name='Queixa Principal')),
                ('historicoDoencaAtual', models.CharField(max_length=1024, verbose_name='Histórico de Doença Atual')),
                ('antecedentesMorbidos', models.CharField(max_length=1024, verbose_name='Antecedentes Mórbidos')),
                ('CondicaoDeVida', models.CharField(max_length=1024, verbose_name='Condição de Vida')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AnamneseEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olhos', models.CharField(max_length=1024, verbose_name='Olhos')),
                ('ouvidos', models.CharField(max_length=1024, verbose_name='Ouvidos')),
                ('sr', models.CharField(max_length=1024, verbose_name='S.R.')),
                ('sc', models.CharField(max_length=1024, verbose_name='S.C.')),
                ('sd', models.CharField(max_length=1024, verbose_name='S.D.')),
                ('sgu', models.CharField(max_length=1024, verbose_name='S.G.U.')),
                ('sn', models.CharField(max_length=1024, verbose_name='S.N.')),
                ('historicoImunizacao', models.CharField(max_length=1024, verbose_name='Histórico de imunização')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
    ]
