# Generated by Django 4.1.4 on 2022-12-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_observacoes_medicacao_examescomplementares_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
        ),
    ]
