# Generated by Django 4.1.4 on 2022-12-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_cpa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CPA',
        ),
    ]
