# Generated by Django 4.1.4 on 2022-12-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_rename_examescomplementares_examecomplementar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicacao',
            name='paciente',
        ),
    ]
